public enum CardinalDirection {
    North, 
    South, 
    East, 
    West,
    NorthEast,
    NorthWest,
    SouthEast,
    SouthWest,
    NorthNorthWest,
    NorthNorthEast,
    EastNorthEast,
    EastSouthEast,
    SouthSouthEast,
    SouthSouthWest,
    WestSouthWest,
    WestNorthWest,
}
